services:
  - type: web
    name: smart-digital-card
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: smart-card-db
          property: connectionString

databases:
  - name: smart-card-db
    plan: free
